### ISSUE TITLE
Team improvement meta issue

### ISSUE THREAD

**Issue by madcowfred** [madcowfred/padherder-issues#450]
- [ ] Allow monster editing from team display - partial #402
- [x] Change the monster selection inputs to the style used in the Add/Edit dialog:

[        ] [ selected name]
[ img ] [ name input ]
- [x] Provide better data in the magic search input dropdown - partial #402:

[        ] Monster name
[ img ] Level, skill, +stats
- [x] Sort the magic search input by ID then 'best' monster (how My Sets chooses the monster to display from multiple choices).
- [ ] Provide some sort of method for filtering monsters - #288
- [ ] Add 'Copy team' feature, both for your own teams and others - #260
